USE ROLE E2E_SNOW_MLOPS_ROLE;
USE WAREHOUSE E2E_SNOW_MLOPS_WH;
USE DATABASE E2E_SNOW_MLOPS_DB;
USE SCHEMA MLOPS_SCHEMA;

CREATE TABLE IF NOT EXISTS ARXIV_PAPERS (
    ARXIV_ID STRING PRIMARY KEY,
    TITLE STRING,
    ABSTRACT STRING,
    AUTHORS STRING,
    CATEGORIES STRING,
    PRIMARY_CATEGORY STRING,
    TOPIC STRING,
    PUBLISHED TIMESTAMP_NTZ,
    UPDATED TIMESTAMP_NTZ,
    ABS_URL STRING,
    PDF_URL STRING,
    TEXT STRING,
    EMBEDDING VECTOR(FLOAT, 384),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ARXIV_PAPERS_STAGING LIKE ARXIV_PAPERS;

CREATE TABLE IF NOT EXISTS ARXIV_QUERIES (
    QUERY_ID STRING DEFAULT UUID_STRING(),
    USER_QUERY STRING,
    TOPIC_FILTER STRING,
    RETRIEVED_ARXIV_IDS STRING,
    NUM_RETRIEVED NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
