USE ROLE E2E_SNOW_MLOPS_ROLE;
USE WAREHOUSE E2E_SNOW_MLOPS_WH;
USE DATABASE E2E_SNOW_MLOPS_DB;
USE SCHEMA MLOPS_SCHEMA;

INSERT INTO ARXIV_EMBEDDINGS (ARXIV_ID, TEXT, EMBEDDING)
SELECT
    p.ARXIV_ID,
    p.TITLE || '\n\n' || p.ABSTRACT AS TEXT,
    SNOWFLAKE.CORTEX.EMBED_TEXT_768('snowflake-arctic-embed-m', p.TITLE || '\n\n' || p.ABSTRACT) AS EMBEDDING
FROM ARXIV_PAPERS p
LEFT JOIN ARXIV_EMBEDDINGS e ON p.ARXIV_ID = e.ARXIV_ID
WHERE e.ARXIV_ID IS NULL;
