USE ROLE E2E_SNOW_MLOPS_ROLE;
USE WAREHOUSE E2E_SNOW_MLOPS_WH;
USE DATABASE E2E_SNOW_MLOPS_DB;
USE SCHEMA MLOPS_SCHEMA;

SELECT COUNT(*) AS NUM_PAPERS FROM ARXIV_PAPERS;

SELECT TOPIC, COUNT(*) AS N
FROM ARXIV_PAPERS
GROUP BY TOPIC
ORDER BY N DESC;

SELECT DATE_TRUNC('DAY', PUBLISHED) AS PUBLISHED_DAY, TOPIC, COUNT(*) AS N
FROM ARXIV_PAPERS
GROUP BY PUBLISHED_DAY, TOPIC
ORDER BY PUBLISHED_DAY DESC, N DESC;
