USE ROLE E2E_SNOW_MLOPS_ROLE;
USE WAREHOUSE E2E_SNOW_MLOPS_WH;
USE DATABASE E2E_SNOW_MLOPS_DB;
USE SCHEMA MLOPS_SCHEMA;

SELECT COUNT(*) AS NUM_PAPERS FROM ARXIV_PAPERS;
SELECT COUNT(*) AS NUM_EMBEDDINGS FROM ARXIV_EMBEDDINGS;

WITH q AS (
    SELECT SNOWFLAKE.CORTEX.EMBED_TEXT_768('snowflake-arctic-embed-m', 'efficient transformer training') AS q_embedding
)
SELECT p.ARXIV_ID, p.TITLE, VECTOR_COSINE_SIMILARITY(e.EMBEDDING, q.q_embedding) AS SIMILARITY
FROM ARXIV_EMBEDDINGS e
JOIN ARXIV_PAPERS p ON e.ARXIV_ID = p.ARXIV_ID
CROSS JOIN q
ORDER BY SIMILARITY DESC
LIMIT 5;
